/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_insightfullogic_honest_profiler_testing_utilities_TestJni */

#ifndef _Included_com_insightfullogic_honest_profiler_testing_utilities_TestJni
#define _Included_com_insightfullogic_honest_profiler_testing_utilities_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_insightfullogic_honest_profiler_testing_utilities_TestJni
 * Method:    generateCpusampleSimpleProfile
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_insightfullogic_honest_1profiler_testing_1utilities_TestJni_generateCpusampleSimpleProfile
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
