/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fk_prof_PerfCtx */

#ifndef _Included_fk_prof_PerfCtx
#define _Included_fk_prof_PerfCtx
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fk_prof_PerfCtx
 * Method:    registerCtx
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_fk_prof_PerfCtx_registerCtx
  (JNIEnv *, jobject, jstring, jint, jint);

/*
 * Class:     fk_prof_PerfCtx
 * Method:    end
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_fk_prof_PerfCtx_end
  (JNIEnv *, jobject, jlong);

/*
 * Class:     fk_prof_PerfCtx
 * Method:    begin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_fk_prof_PerfCtx_begin
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
