/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fk_prof_TestJni */

#ifndef _Included_fk_prof_TestJni
#define _Included_fk_prof_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fk_prof_TestJni
 * Method:    generateCpusampleSimpleProfile
 * Signature: (Ljava/lang/String;)Z
 */
    JNIEXPORT jboolean JNICALL Java_fk_prof_TestJni_generateCpusampleSimpleProfile
    (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
