#!/bin/bash
set -x

PAC=fk-prof-ui
CMD="$1"

USER=$PAC
GROUP=fk-prof-dev

USER_ID=6015
GID=6030
PORT={{PORT}}

if [ "$1" == "configure" ] ; then

    #creating user if it doesnt exist
    if ! getent group $GROUP > /dev/null; then
        groupadd -g $GID $GROUP
    fi

    if ! getent passwd $USER_ID > /dev/null; then
        adduser --system --uid $USER_ID --home /usr/share/$PAC --no-create-home \
        --ingroup $GROUP --disabled-password --shell /bin/false \
        $USER
    fi

    if [ "$PAC" ]; then
      LOG_DIR="/var/log/${PAC}"
      [ -d "$LOG_DIR" ] || mkdir -p $LOG_DIR
      chown -R $USER:$GROUP /usr/share/$PAC
      [ -d "$LOG_DIR" ] && chown -R $USER:$GROUP $LOG_DIR && chmod 777 $LOG_DIR
    fi

	cd /usr/share
	mkdir -p $PAC
	tar xzf $PAC.tgz -C $PAC

	echo "Starting $PAC service"
	cd /usr/share/$PAC
    NODE_ENV=production PORT={{PORT}} node_modules/forever/bin/forever start server.js
fi

exit 0
