#!/bin/bash -e
set -x

PORT=$1
DIST_DIR="./dist"
DEBIAN_DIR="DEBIAN"
PACKAGE_NAME="fk-prof-ui"
DEST_PATH="$DIST_DIR/usr/share/$PACKAGE_NAME"

# set correct permissions for DEBIAN scripts
chmod 0775 $DEBIAN_DIR/postinst $DEBIAN_DIR/postrm $DEBIAN_DIR/prerm

# building assets
npm install
npm run prod-build --bail

mkdir -p $DEST_PATH
rm -rf $DEST_PATH/*

echo "Copying DEBIAN into ${DIST_DIR}..."
cp -r $DEBIAN_DIR $DIST_DIR/

echo "Copying app files into ${DEST_PATH}..."
cp -r  server.js package.json public $DEST_PATH

export VERSION=$(date +%Y%m%d-%H%M)
echo $VERSION

find $DIST_DIR/$DEBIAN_DIR -type f | xargs sed -i "s/_VERSION_/$VERSION/g"
find $DIST_DIR/$DEBIAN_DIR -type f | xargs sed -i "s/_PACKAGE_/$PACKAGE_NAME/g"
sed -i "s/{{PORT}}/${PORT}/g" $DIST_DIR/$DEBIAN_DIR/postinst

echo 'Finished creating the Deb folder structure. Yayyy!'